### ISSUE TITLE
GET JSONPath Better Logic card not working

### ISSUE THREAD

**Issue by DieterKoblenz** [irritanterik/homey-http-request-actions#11]
Hi Erik,

Can't get this card to work with the following url: "http://192.168.1.155:5555/api/results" as it gives me a "not_found" error. The regular http get card does perform a valid get request.

**Comment by irritanterik** [comment]
Wat response does the request get and what is your jsonpath expression?

**Comment by DieterKoblenz** [comment]
I must have made an error this morning (even though I checked twice with a online json path explorer).. Because it's working now.
