### ISSUE TITLE
Unable to add xml code to action card

### ISSUE THREAD

**Issue by rhannink** [irritanterik/homey-http-request-actions#12]
I am trying to post an XML soap message to my TV to turn it of. But when I use the POST XML action card, I am unable to paste the required XML code in the second parameter field:

`<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:X_SendIRCC xmlns:u="urn:schemas-sony-com:service:IRCC:1"><IRCCCode>AAAAAQAAAAEAAAAvAw==</IRCCCode></u:X_SendIRCC></s:Body></s:Envelope>`

**Comment by irritanterik** [comment]
Unfortunately the Homey interface escapes all tags on the flow card text input fields. I have not found a way to work around this.

**Comment by rhannink** [comment]
Rik,

Thanks, good tip, the following code is accepted as input in the action card:

`&lt;?xml version="1.0" encoding="utf-8”?&gt;&lt;s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"&gt;&lt;s:Body&gt;&lt;u:X_SendIRCC xmlns:u="urn:schemas-sony-com:service:IRCC:1"&gt;&lt;IRCCCode&gt;AAAAAQAAAAEAAAAvAw==&lt;/IRCCCode&gt;&lt;/u:X_SendIRCC&gt;&lt;/s:Body&gt;</s:Envelope&gt;`
