### ISSUE TITLE
connect ehostunreach does not fire else action

### ISSUE THREAD

**Issue by ChMonkeyWay** [irritanterik/homey-http-request-actions#13]
Hi,
I am checking for an http server in the local network. But if this is not reachable it does not fire my else actions.
Currently I use the "Get Code is" 200 but if this fails it due to the host is not available it does not fire the else action. Is it possible to change/add?
Thanks.
Cheers,
Christian

**Comment by irritanterik** [comment]
This is supported by the "net scan" app. This will give you triggers based on available ip devices.

**Comment by ChMonkeyWay** [comment]
hm okay this does not work for me. I am using a very simple http server on a arduino board to get PH values and currently I don't know why I can not ping it. So my hope was to have a solution with this.

**Comment by ChMonkeyWay** [comment]
also a timeout does not fire else actions

**Comment by irritanterik** [comment]
I tested on Homey 2.0.0 with timeout and ENOTFOUND in conditions; both triggers the else actions. Can you confirm this?

**Comment by irritanterik** [comment]
Dit some additions on this. Condition cards will now return statuscodes 0 (error) and 1 (timeout), so condition card handling can check these cases better. (v 2.0.7)
