### ISSUE TITLE
error 302

### ISSUE THREAD

**Issue by Daaann** [irritanterik/homey-http-request-actions#16]
Want to send https://webehome.com/Public/login.aspx?LoginName=xxxxx&Password=xxxxxx&Action=home to my alarm but can not make it work. should I use GET or GET (querty) or something else? Receives error code 302.

**Comment by irritanterik** [comment]
Hi @Daaann. Use the GET Query card (A21) with the url query as a json. Example:

```
url parameter: https://webehome.com/Public/login.aspx
query parameter: {"LoginName": "xxxxx", "Password": "xxxxxx", "Action": "home"}

```

**Comment by Daaann** [comment]
Have tested to go just as you wrote but became no difference. Got green ok but nothing happens.

**Comment by irritanterik** [comment]
What debug info do you get in the Homey Logger app (https://apps.athom.com/app/gov.nsa.logger)? A green ok on the card in the flow editor means the API does not return an error.

**Comment by Daaann** [comment]
{"datetime":"2018-11-19T19:31:21.314Z","message":"A21 action.http_get_json","data":{"status":302,"response":"\r\nObject moved to here.
--

**Comment by Daaann** [comment]
Cannot GET /%22/error.html?aspxerrorpath=/Public/login.aspx\%22

**Comment by irritanterik** [comment]
`%22` converts to " in html. Are you sure the first parameters in Homey with the URL does not contains the " character?

**Comment by Daaann** [comment]
Copy and paste this



Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: Erik van Dongen <notifications@github.com>
Datum: 2018-11-19 21:34 (GMT+01:00)
Till: irritanterik/homey-http-request-actions <homey-http-request-actions@noreply.github.com>
Kopia: Daaann <christiansson_dan@hotmail.com>, Mention <mention@noreply.github.com>
Rubrik: Re: [irritanterik/homey-http-request-actions] error 302 (#16)


%22 converts to " in html. Are you sure the first parameters in Homey with the URL does not contains the " character?

**Comment by Daaann** [comment]
Didn't find any solution to this yet. No more ideas? The log still says: Cannot GET /%22/error.html?aspxerrorpath=/Public/login.aspx\%22.

Sent looks like this: {"datetime": "2019-01-08T16: 15: 29.008Z", "message": "A21 action.http_get_json", "data": {"args": {"url": " https://webehome.com/Public/login.aspx "," data ":" {\ _ "LoginName": "xxxxxx", "Password": "xxxxxxxx", "Action") "clear"} "," method ":" get "," urlOptions ": {" uri ":" https://webehome.com/Public/login.aspx "," query ": {" LoginName ":" xxxxxx "," Password ":" xxxxxxxx "," Action "," clear "}," timeout ": 30000}}}

**Comment by irritanterik** [comment]
Looks like jou have some spaces in the request field before and after the url

**Comment by Daaann** [comment]
Looks like this now but is the same error.
{"datetime": "2019-01-08T16: 51: 21.813Z", "message": "A21 action.http_get_json", "data": {"args": {"url": "https: // webehome. com / public / login.aspx "" data ":" {\ "Accommodations Name \": \ "xxxxxx \", \ "Password \": \ "xxxxxxxxxxx \", \ "Action \": \ "clear \" } "}," method ":" get "," urlOptions ": {" uri ":" https://webehome.com/Public/login.aspx "," query ": {" Accommodations Name ":" xxxxxx " "Password": "xxxxxxxxxxx", "Action", "clear"}, "timeout": 30000}}}

**Comment by irritanterik** [comment]
302 is a http redirect code. To what endpoint do you get redirected when requesting the url in a browser?

**Comment by Daaann** [comment]
If I take both rows and put it together it will be like this in the browser: Something went wrong, please tell us about it. Click on this link to get back to WeBeHome (b3307).

**Comment by Daaann** [comment]
But this is how it works in your browser: https://webehome.com/Public/login.aspx?LoginName=XXXXX&Password=XXXXX&Action=home

and then I enter my alarm page logged in and selected mode activated

**Comment by irritanterik** [comment]
Does the browser gets a http 302 redirect? You can check this with the browser debug tools and then network monitor.

**Comment by Daaann** [comment]
Now I don't really understand .. is there in all browsers?

**Comment by Daaann** [comment]
Now I found out if I put the line in the browser so there is get 302

**Comment by irritanterik** [comment]
Fixed with 90e74192bffa9758fc9ed3afc7df42f5afb6ac41

**Comment by irritanterik** [comment]
App store approval is awaiting Athom code review.

**Comment by Daaann** [comment]
Okay so you've fixed an update! Looking forward to this! Thanks! How long does it usually take before approval?

**Comment by irritanterik** [comment]
Up to a week, but considering homey v2 stable launch I expect it to be shorter

**Comment by Daaann** [comment]
Okay tried to install directly from your zip file but came in error at the end.

Pre-processing app ...
✓ Validating app ...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App ...
  - App size: 2.55 MB
✓ Installing Homey App on `Homey` (http://192.168.1.169:80) ...
× incompatible_app_version

**Comment by irritanterik** [comment]
Wait 4 days, install Homey v2 then try again  ;)

**Comment by Daaann** [comment]
Unfortunately 2.0 did not solve my problems.
You do not have any other ideas about what might be wrong

**Comment by irritanterik** [comment]
So new app version installed? You could try homey v2 native web request action.

**Comment by Daaann** [comment]
excuse me but where do I find it?


Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: Erik van Dongen <notifications@github.com>
Datum: 2019-01-17 07:52 (GMT+01:00)
Till: irritanterik/homey-http-request-actions <homey-http-request-actions@noreply.github.com>
Kopia: Daaann <christiansson_dan@hotmail.com>, Mention <mention@noreply.github.com>
Ämne: Re: [irritanterik/homey-http-request-actions] error 302 (#16)


So new app version installed? You could try homey v2 native web request action.

**Comment by Daaann** [comment]
where do I find this? "homey v2 native web request action"

**Comment by irritanterik** [comment]
https://blog.athom.com/homey-v2-0-insights-alarms-logic/
