### ISSUE TITLE
Siri shortcuts

### ISSUE THREAD

**Issue by Patrick1610** [irritanterik/homey-http-request-actions#17]
Ik had een shortcut voor Siri gemaakt waarin ik een event stuurde naar deze app. Op basis daarvan ging mijn status op 'Slapen'. Dit werkte voorheen vlekkeloos, maar nu ineens niet meer. 
Enig idee waar dit plotseling aan kan liggen?

**Comment by irritanterik** [comment]
Kan je de flow nog steeds starten als je de url via de browser aanroept?

**Comment by Patrick1610** [comment]
Nee, dat doet hij ook niet.

**Comment by irritanterik** [comment]
Wat doet hij wel? Een aantal punten die je kan nalopen zijn:
- Kan je geen enkele flow meer op deze manier starten, of is het probleem specifiek bij deze flow?
- Hoe staan de instellingen van de app? Vereis je authenticatie? Gebruik je de whitelist functie? (zo ja, komen ip-adressen nog overeen? Gebruik je geldige tokens in de request?)
- Welke informatie staat er in de logger op het moment dat je de url aanroept? (zie Homey Logger App)
- Geeft een aanroep van de url een fout terug?

**Comment by Patrick1610** [comment]
Super bedankt voor het meedenken, hieronder wat meer informatie: 
Kan je geen enkele flow meer op deze manier starten, of is het probleem specifiek bij deze flow? Geen enkele start meer
Hoe staan de instellingen van de app? Vereis je authenticatie? Gebruik je de whitelist functie? (zo ja, komen ip-adressen nog overeen? Gebruik je geldige tokens in de request?) Geen authenticatie vereist EN whitelist in gebruik met static IP's
Welke informatie staat er in de logger op het moment dat je de url aanroept? (zie Homey Logger App) Ik zal deze app eens downloaden en bekijken, die heb ik momenteel niet
Geeft een aanroep van de url een fout terug? Voorheen kreeg ik ‘webpagina niet gevonden’ zojuist de app verwijderd en opnieuw geïnstalleerd en krijg nu de volgende melding: {"status":401,"result":"no_auth_method_found"}

**Comment by irritanterik** [comment]
Status 401 duidt erop dat de instelling voor authenticatie aan staat. Verzeker je ervan dat je na het uitzetten van die instelling de app herstart.
