### ISSUE TITLE
Get number

### ISSUE THREAD

**Issue by HenricAsk** [irritanterik/homey-http-request-actions#19]
Can you implement so that you can send a numeric value to Homey through Incoming GET card.
I'm sending a temperature to Homey and I would like to compare that value if it's less or greater than a set value.
Is this someting you can do?

**Comment by irritanterik** [comment]
Have you tried this with the trigger card? Add a \value after the event name and that value is available as a token on the trigger card.

**Comment by HenricAsk** [comment]
Yes but that value is a string-tag and cannot be used as a numeric tag for culculations.

**Comment by irritanterik** [comment]
Is this on Homey v2.x or v1.5.x?

**Comment by HenricAsk** [comment]
1.5.x

Den sön 6 jan. 2019 15:28 skrev Erik van Dongen <notifications@github.com>:

**Comment by irritanterik** [comment]
Added in 2.0.7 (pending appstore approval)
