### ISSUE TITLE
2.0.4 broken!

### ISSUE THREAD

**Issue by herwarth** [irritanterik/homey-http-request-actions#22]
cannot start the app again since updated to 2.0.4 using homey 2.0

**Comment by irritanterik** [comment]
Thanks for reporting. Duplicate of #20 and #21. Fix is pending Athom approval

**Comment by cento007** [comment]
Deze app is onverwachts gestropt. De v2.0.3 had ik werkend zonder problemen

**Comment by irritanterik** [comment]
Its a known issue, I made a fix version yesterday. This fix 2.0.5 is awaiting app store apporval.

**Comment by cento007** [comment]
Thanks app starts and works again!

**Comment by irritanterik** [comment]
Thanks to Athom approving the update today.
