### ISSUE TITLE
How to work with curl in homey 2.0

### ISSUE THREAD

**Issue by basd82** [irritanterik/homey-http-request-actions#23]
Hi have multiple espeasy device that report back when they are switched on in homey 1.5 i used webhook to turn the virtual switch on and off but now i can't whitelist ip's anymore

I use this url: http://192.168.200.90/api/app/com.internet/Zetaanrechtuit for example
but i get:

{"code":401,"error":"not_logged_in","error_description":"You need to log in to access this resource"}

How can i make this work using a GET ?

**Comment by irritanterik** [comment]
Because of SDK changes in Homey V2 whitelisting is currently not possible. You can however disable authentication in the app settings. Don't forget to restart the app for this setting to have effect.
