### ISSUE TITLE
Flows

### ISSUE THREAD

**Issue by nesheimt** [irritanterik/homey-http-request-actions#24]
Hi
I´m sending the following to my Homey:

http://192.168.1.7:80/api/app/com.internet/doorman/unlock

and I use the "Incomming GET" card. "doorman" triggers the flow(using your http-app) AND value=unlock(using builtin Logic) THEN open door (using Doorman app). This worked fine in v1 but in v2 this seems not to work for some reason. Please advice.

**Comment by irritanterik** [comment]
Can you add screenshots of your flow trigger and condition?

**Comment by nesheimt** [comment]
Hi
Thanks for quick response. Here are screenshot of my flow(please see post below)

If I remove the “unlock” from the http-command I send and from the flow I can make the flow trigger. But I need the value in some cases in Homey.
I had about similar 15 of these working on v1

Best regards
 Torbjørn Nesheim

**Comment by nesheimt** [comment]
![img_0524](https://user-images.githubusercontent.com/17417348/51633986-49a7ef80-1f53-11e9-9efb-8671d323c7a4.PNG)
![img_0523](https://user-images.githubusercontent.com/17417348/51633987-49a7ef80-1f53-11e9-9c93-508074cdec87.PNG)
![img_0525](https://user-images.githubusercontent.com/17417348/51633989-4a408600-1f53-11e9-8436-156320e52374.PNG)

**Comment by irritanterik** [comment]
Thanks. Bad issue, all triggers are dead. I will look into in tonight.

**Comment by irritanterik** [comment]
Conversion of non-numeric values coused a NaN value passed to flow trigger handling resulting in homey not triggering flows.
Fixed with 882d2824b7e98582c05a058ba4213013d44aecc3 (app version 2.0.8).
App update is now pending Athom approval.

**Comment by nesheimt** [comment]
Looking forward to the new version, thanks!
Is the approval some automatic process, or man-in-the-loop?

**Comment by irritanterik** [comment]
Man-in-the-loop. Will take a few days. If you can't wait.. use numbers instead of strings (so 1 instead of "lock")

**Comment by irritanterik** [comment]
2.0.8 is now available in the app store.

**Comment by nesheimt** [comment]
It works, smarthouse is back in business, thanks!
