### ISSUE TITLE
please support get json path logica

### ISSUE THREAD

**Issue by herwarth** [irritanterik/homey-http-request-actions#25]
now we only have: get json path betterlogic.
I want to phase out better logic, because logica in homey 2.0 is good enough

**Comment by irritanterik** [comment]
You can use card A23 combined with T80 as an alternative.
Unfortunantly the Homey SDK does not support setting values from apps like we do now with the better logic variables.

**Comment by herwarth** [comment]
a23 and t80? huh can you clarify?

**Comment by irritanterik** [comment]
Every card has a number which corresponds with the description in the app store and in the flow cards:
![20190201_181603](https://user-images.githubusercontent.com/15232724/52138740-519c1980-264e-11e9-9e78-e19a7ecc2a26.jpg)

**Comment by irritanterik** [comment]
English, as visible in the appstore:

*GET JSONpath trigger value*
(A23) Extract a value from a JSON or XML formatted GET response and trigger other flows with this value available as a token (card T80).

*JSONpath value*
(T80) Trigger a flow from cards A23 and A81 by using the same value in the 'trigger'-field.

In the first flow you use card A23. In a second flow, triggered by card T80 you have the extracted value available as a token. This token can be used with the build in logic cards. The trigger names in both cards should be the same.

**Comment by herwarth** [comment]
hallo

screenshot toegevoegd. dit run ik in een constante loop. elke 5 sec. maar 
nu staat de waarde in een trigger die ik even alarmtrigger heb genoemd. hoe 
doe ik de tweede flow om de inhoud van die trigger in een variabele te duwen?

Op 1 februari 2019 18:23:20 schreef Erik van Dongen <notifications@github.com>:
