### ISSUE TITLE
JSON data to (better)logic Homey

### ISSUE THREAD

**Issue by Patrick1610** [irritanterik/homey-http-request-actions#27]
Hi, 

I want to integrate Tautulli with Homey and control my lights by doing the following. 
On a certain watched percentage, I let Tautulli sent a POST (WatchedPlex) to Homey, this works fine. 
I let Tautulli sent the following JSON data with the post: 

{remaining_duration} | The remaining duration (in minutes) of the stream.

I want Homey to save the remaining time as a variable (logic of better logic) so I can use that duration for my lights. I think this should be done with the A80 card. What should I fill in? 

Thanks in advance!

**Comment by irritanterik** [comment]
Native Homey Logic is not yet supported so way to go for now is card A80.

What is the exact post request?
If T30 then A80
If the json body is `{remaining_duration: 50}` the correct JSONpath expression would be `$.remaining_duration`

**Comment by Patrick1610** [comment]
![img_1dbf3d987615-1](https://user-images.githubusercontent.com/6585375/53243715-115a1500-36a9-11e9-936c-f50203a86446.jpeg)
![img_0523](https://user-images.githubusercontent.com/6585375/53243716-115a1500-36a9-11e9-90a5-2c44e3983f59.PNG)
![img_0524](https://user-images.githubusercontent.com/6585375/53243973-cd1b4480-36a9-11e9-9e7c-f3b13666792d.jpg)

Thanks for thinking with me!  
I have now set it up like this, but the Better Logic value does not change at all with this setting either.  

Also, when I run a test notification with just "5", the value does not change

I thought, the {remaining_duration} tag from tautulli is a placeholder and just becomes the number of minutes. With the started notification, I only see "Star Wars|, not "{Movie_title: Star Wars}".

**Comment by irritanterik** [comment]
`{5}` is not a valid JSON formatted body and can't be parsed successful with my app unfortunately.
You could do a last try with JSONpath `$[0]`. That could extract a number from within straight brackets like `[5]`.

**Comment by Patrick1610** [comment]
Alright! I also see I can manually edit the JSON Body from within Tautulli. 

Does that give me more possibilities? 
Can I make a JSON body that works, with the {remaining_duration} tag in it? 

EDIT: added screenshots
<img width="688" alt="screenshot 2019-02-22 at 14 16 03" src="https://user-images.githubusercontent.com/6585375/53245016-d528b380-36ac-11e9-8fd9-b9848dbdc130.png">
<img width="600" alt="screenshot 2019-02-22 at 14 16 16" src="https://user-images.githubusercontent.com/6585375/53245017-d528b380-36ac-11e9-8c5d-47988717221a.png">

**Comment by Patrick1610** [comment]
Here is a screenshot of a standard JSON body that is used on a movie start event. 

<img width="678" alt="screenshot 2019-02-22 at 14 31 20" src="https://user-images.githubusercontent.com/6585375/53245689-aad7f580-36ae-11e9-9d7a-c38095da3392.png">

**Comment by irritanterik** [comment]
Try: 
```
{
  "remaining_duration": {remaining_duration}
}
```

**Comment by Patrick1610** [comment]
Thanks! I added that on the automatic 'Watched notification', and nothing happened. 
But.. When I sent the following as a test notification, it does work: 

{
  "remaining_duration": 5
}

So I guess the problem is with the output of the {remaining_duration} tag? Or could I try something else?

**Comment by Patrick1610** [comment]
Also, is there any difference in using GET or POST for my usage? Currently I use POST (don't know why, but it works.. 👍 )

**Comment by Patrick1610** [comment]
I got it! The following command works! 

{
  "remaining_duration": "{remaining_duration}"
}

Thanks for helping, you're the best! Now the lights wil dim slowly on during the movie credits 👍

**Comment by irritanterik** [comment]
Great! Have fun!
