### ISSUE TITLE
Please update manual / instructions in settings (very smal bug)

### ISSUE THREAD

**Issue by B3rt** [irritanterik/homey-http-request-actions#29]
It seems that the link to connect via external connextion has changed in homey v2.

The old link is: (v1.5.x)
https://HOMEYCLOUDID.homey.athom.com/api/app/com.internet/event/trigger

In Homey 2 this is:
https://HOMEYCLOUDID.connect.athom.com/api/app/com.internet/event/trigger

In your instructions in settings there is still the old link displayed, so after updating from 1.5 to v2 external http request cards do not work anymore, the link should be updated but this is nowhere mentioned and in settings the old link is mentioned

**Comment by irritanterik** [comment]
Thank you for your remark. Please submit a PR.

**Comment by irritanterik** [comment]
Improved in v 2.0.11
