### ISSUE TITLE
delay http request starting a flow with siri

### ISSUE THREAD

**Issue by jorritv8hoven** [irritanterik/homey-http-request-actions#30]
since the last update 2.0.10 I have had problems with the http request flow cards in combination with siri. When I give siri a command, a flow is activated. There is now a delay of 6 minutes. Eventually the flow is started, but it takes a long time. Is there a solution for this?

**Comment by irritanterik** [comment]
Wow. 6 minutes is a long time! Did you rebooted Homey? What is the delay when calling the request url manual in a browser?

**Comment by jorritv8hoven** [comment]
Hello Erik,

after the reboot this morning it still didn't work. After I tried it manually via the browser it worked immediately. Then again with siri. Thanks for your quick response!

gr Jorrit

**Comment by irritanterik** [comment]
Great
