### ISSUE TITLE
Cannot select variable for GET JSONpath Better Logic

### ISSUE THREAD

**Issue by chixxi** [irritanterik/homey-http-request-actions#31]
I think I am doing a stupid error, but I just can't figure this out.

I want to get the temperature from a particle photon which is available via a http get request by using the card "JSONpath Better Logic"

Request:
https://api.particle.io/v1/devices/DEVICE/target1?access_token=XYZ

Response:
`{"cmd":"VarReturn","name":"temp1","result":5.25,"coreInfo":{"last_app":"","last_heard":"2019-08-02T12:09:08.114Z","connected":true,"last_handshake_at":"2019-08-02T08:17:26.445Z","deviceID":"XYZ","product_id":6}}`

Homey version:
v2.5.1-rc.3

App version:
v2.0.11

Issue:
I simply can not select the variable to set. I have Boolean, String and Numeric variables set up, none are showing up. What am I doing wrong?

![image](https://user-images.githubusercontent.com/1770007/62370814-668d3300-b533-11e9-91f1-394555c89e59.png)

**Comment by irritanterik** [comment]
Can you send in a report/log via the homey settings?

**Comment by chixxi** [comment]
Oh lol, bet it ia cause I am using standard and not better logic variables.

**Comment by chixxi** [comment]
Report: ecf22736-dbb9-41fc-a938-e79af0146f1a

**Comment by chixxi** [comment]
Sure, stupid me was adding variables in the wrong menu. Sorry to have bothered you.

**Comment by irritanterik** [comment]
No problem. Want to add support for standard variables some day, but that's not possible right now.
