### ISSUE TITLE
JSON Post "Unexpected token: in JSON at position 3"

### ISSUE THREAD

**Issue by errno111** [irritanterik/homey-http-request-actions#32]
Hi,

I am able to run the following JSON Post from a software called Fiddler

![image](https://user-images.githubusercontent.com/53953146/62825592-d4c69b00-bbae-11e9-9a87-5ab9569ea87b.png)

But when i make a new HTTP Request flow cards POST JSON that looks like this it wont work:

In the first textbox:
http://192.168.1.141:8123/api/services/light/turn_on

and in the second text box:

{ 
"authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlOTA3Y", 
"content-type": "application/json",
"host": "192.168.1.141:8123", 
"Content-Length": "62", 
"entity_id": "light.hall_uppe_tak", 
"brightness": "0"
}

and i get the following error: "Unexpected token: in JSON at position 3"

What am i doing wrong? =)

Best Regards Jonas

**Comment by irritanterik** [comment]
Responsed with pm on Homey Community Forum
