### ISSUE TITLE
User parameter rendering

### ISSUE THREAD

**Issue by kerkenit** [irritanterik/homey-http-request-actions#7]
Hello, first of all thanks for this awesome app for Homey. I Love It.
I'm new to Homey, and I'm don't know if it it is an issue of this app or Homey it self, but i start to report her. Maybe you can take a look at the issue.
I'm triggering my Domoticz system by using JSON url's.
I'm filling in the url for example /json.htm?type=command&param=switchlight
If I save it's going oké. So far so good. It's executed well.
The problem is, when i'm reopening the flow in Homey, the &param is rendered as HTML enitiy, so command&param whill become command¶m.
Is this in your app fixable? I guess, Homey should work this way, for the other cards.

I'm waiting for your reply. Thanks in advance!
<img width="273" alt="schermafbeelding 2016-04-21 om 19 53 28" src="https://cloud.githubusercontent.com/assets/13370203/14719126/cb4ac3aa-07fa-11e6-8b6e-813e3b9d6c3d.png">

**Comment by matjaz** [comment]
`&para;` is html entity (¶). This sounds like a Homey bug. I remember there was a similar issue with copy/pasting.

**Comment by irritanterik** [comment]
Check the apps discussion on the athom forum please. You'll need the get
json card for this. (put the request query parameters in a valid json)
Op 21 apr. 2016 19:55 schreef "Kerk en IT" notifications@github.com:
