### ISSUE TITLE
Post command changes after saving flow

### ISSUE THREAD

**Issue by posthok** [irritanterik/homey-http-request-actions#8]
![http flow 1](https://cloud.githubusercontent.com/assets/6661318/17053260/7413ffee-5001-11e6-8a4c-cba27e1d17e6.jpeg)
After saving this flow this happens.
![http flow](https://cloud.githubusercontent.com/assets/6661318/17053272/8afbfbe4-5001-11e6-8fad-31f093d6a1d5.jpeg)

**Comment by irritanterik** [comment]
Have you typed the values instead of pasting it from a rich text editor?
What browser/platform do you use?

Op 22 jul. 2016 11:43 schreef "posthok" notifications@github.com:

**Comment by posthok** [comment]
text input in Chrome.
after saving it runs once and after that the text changes.
After changing the text and saving it, it happens again.
Running 1.31 by the way

**Comment by irritanterik** [comment]
Ok, I'll investigate after my holiday. As a work around you could use the geek options in this card. With that you can put the query parameters in a json structure.

**Comment by posthok** [comment]
Thanx

**Comment by posthok** [comment]
Also in the geek version the input changes instantly from type=command&param=switchlight to type=command¶m=switchlight when saved.
I'm using 8.39 btw.
Working in chrome and windows 10 app, the result stays the same

**Comment by irritanterik** [comment]
With geek options you must input query parameters JSON formatted: 

```
{"method":"post"
,"protocol":"http:"
,"hostname":"192.168.0.10"
,"path":"/service"
,"query":{"type":"command","param":"switchlight"}
}
```

**Comment by irritanterik** [comment]
`&para;` means ¶ according to HTML. Unfortunantly somewere in the Homey framework `&para` (without semicolon) is interpreted as HTML character.  You'll also see this behaviour on other flow cards:
![image](https://cloud.githubusercontent.com/assets/15232724/17459360/2d555906-5c34-11e6-92d3-e1c56c166084.png)

For now, you can switch the parameters in your post url, so variable `param` follows the `?` and variable `type` follows `&`:
`http://192.168.0.x:port/service?param=switchlight&type=command`

**Comment by irritanterik** [comment]
I reported this issue https://github.com/athombv/homey/issues/767

**Comment by posthok** [comment]
Ok thanx that worked.
