### ISSUE TITLE
url misinterpreted 

### ISSUE THREAD

**Issue by Radiotechniman** [irritanterik/homey-http-request-actions#9]
when adding the following url
http://ip address/json.htm?type=command&param=switchscene&idx=9&switchcmd=On
it gets saved  as 
http://ip address/json.htm?type=command¶m=switchscene&idx=9&switchcmd=On

the interpretation of the &para seems to be wrong 
(this is from the domoticz api :
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Scenes_.2F_Groups )

**Comment by irritanterik** [comment]
Its a problem with homey's escaping mechanism. Beause `&para` is a HTML escape value. You can work around by making `param` the first parameter in your url:
`http://ip address/json.htm?param=switchscene&type=command&idx=9&switchcmd=On`

**Comment by Radiotechniman** [comment]
yeah... i should've thought of that too :-/

Thanks
